MyTelegramBot/Controllers/AvailableСitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyTelegramBot.Controllers
{
    [Produces("application/json")]
    public class AvailableСitiesController : Controller
    {

        MarketBotDbContext db;
        public IActionResult Index()
        {
            db = new MarketBotDbContext();


            return View(db.AvailableСities.ToList());
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            db = new MarketBotDbContext();

            var city = db.AvailableСities.Where(a => a.Id == id).FirstOrDefault();

            if (city != null)
            {
                db.Remove(city);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Add(string name)
        {
            db = new MarketBotDbContext();

            if (name != null && name != "")
            {
                AvailableСities available = new AvailableСities
                {
                    CityName = name,
                    Timestamp = DateTime.Now
                };

                db.AvailableСities.Add(available);

                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

MyTelegramBot/Views/AvailableСities/Index.cshtml
@model IEnumerable<MyTelegramBot.AvailableСities>
@{
    Layout = "_Layout";
}
<!DOCTYPE html>
<h3>Список доступных городов от куда можно оформлять заказ</h3>

@using (Html.BeginForm("Add", "AvailableСities", FormMethod.Get))
{
    <label>Введите название города</label>
    @Html.TextBox("name")
    <input type="submit" value="Добавить" class="btn btn-success" />
}

<table class="table">
    <tr>
        <td>Название</td>
        <td>Дата добавления</td>
        <td>Удалить</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr><td>@item.CityName</td>
            <td>@item.Timestamp</td>
            <td><a href="~/AvailableСities/Delete/@item.Id">Удалить</a></td>
        </tr>
    }
</table>