MyTelegramBot/Controllers/PayConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyTelegramBot.Services;
namespace MyTelegramBot.Controllers
{
    [Produces("application/json")]
    public class PayConfigController : Controller
    {
        PaymentTypeConfig PaymentTypeConfig;

        PaymentTypeEnum PaymentTypeEnum;

        MarketBotDbContext db;

        public IActionResult Qiwi()
        {
            db = new MarketBotDbContext();

            PaymentTypeEnum = PaymentTypeEnum.Qiwi;

            List<PaymentTypeConfig> list = new List<PaymentTypeConfig>();

            list = db.PaymentTypeConfig.Where(p => p.PaymentId == PaymentType.GetTypeId(PaymentTypeEnum)).OrderByDescending(p => p.Id).ToList();

            PaymentType paymentType = db.PaymentType.Find(PaymentType.GetTypeId(PaymentTypeEnum));

            Tuple<List<PaymentTypeConfig>, PaymentType> model = new Tuple<List<PaymentTypeConfig>, PaymentType>(list, paymentType);

            return View("Qiwi", model);
        }

        public IActionResult Litecoin()
        {
            db = new MarketBotDbContext();

            PaymentTypeEnum =  PaymentTypeEnum.Litecoin;


            PaymentTypeConfig = db.PaymentTypeConfig.Where(p => p.PaymentId == PaymentType.GetTypeId(PaymentTypeEnum)).OrderByDescending(p => p.Id).FirstOrDefault();

            if (PaymentTypeConfig == null)
            {
                PaymentTypeConfig = new PaymentTypeConfig
                {
                    Host = "127.0.0.1",
                    Login = "root",
                    Pass = "toor",
                    Port = "9332",
                    Enable = true,
                    PaymentId = PaymentType.GetTypeId(PaymentTypeEnum)
                };

            }

            ViewBag.Title = "Litecoin";
            ViewBag.Text = "В папке с установленными Litecoin Core создайте бат файл.Сохраните и запустите этот бат файл и дождитесь синхронизации базы данных (Размер базы данных более 10гб)." +
                "Содержимое бат файла:";
            ViewBag.Bat = "litecoin-qt.exe -server -rest -rpcuser=root -rpcpassword=toor -rpcport=9332";
            
            return View("CryptoCurrency", PaymentTypeConfig);
        }

        public IActionResult BitcoinCash()
        {
            db = new MarketBotDbContext();

            PaymentTypeEnum = PaymentTypeEnum.BitcoinCash;

            PaymentTypeConfig = db.PaymentTypeConfig.Where(p => p.PaymentId == PaymentType.GetTypeId(PaymentTypeEnum)).OrderByDescending(p => p.Id).FirstOrDefault();

            if (PaymentTypeConfig == null)
            {
                PaymentTypeConfig = new PaymentTypeConfig
                {
                    Host = "127.0.0.1",
                    Login = "root",
                    Pass = "toor",
                    Port = "8332",
                    Enable = true,
                    PaymentId = PaymentType.GetTypeId(PaymentTypeEnum)
                };

            }

            ViewBag.Title = "Bitcoin Cash";
            ViewBag.Text = "В папке с установленными Bitcoin Cash Core создайте бат файл.Сохраните и запустите этот бат файл и дождитесь синхронизации базы данных (Размер базы данных более 150гб)." +
                "Содержимое бат файла:";
            ViewBag.Bat = "bitcoin-qt.exe -server -rest -rpcuser=root -rpcpassword=toor -rpcport=8332";

            return View("CryptoCurrency", PaymentTypeConfig);
        }

        public IActionResult Bitcoin()
        {
            db = new MarketBotDbContext();

            PaymentTypeEnum = PaymentTypeEnum.Bitcoin;

            PaymentTypeConfig = db.PaymentTypeConfig.Where(p => p.PaymentId == PaymentType.GetTypeId(PaymentTypeEnum)).OrderByDescending(p => p.Id).FirstOrDefault();

            if (PaymentTypeConfig == null)
            {
                PaymentTypeConfig = new PaymentTypeConfig
                {
                    Host = "127.0.0.1",
                    Login = "root",
                    Pass = "toor",
                    Port = "8332",
                    Enable = true,
                    PaymentId = PaymentType.GetTypeId(PaymentTypeEnum)
                };

            }

            ViewBag.Title = "Bitcoin Cash";
            ViewBag.Text = "В папке с установленными Bitcoin Core создайте бат файл.Сохраните и запустите этот бат файл и дождитесь синхронизации базы данных (Размер базы данных более 180гб)." +
                "Содержимое бат файла:";
            ViewBag.Bat = "bitcoin-qt.exe -server -rest -rpcuser=root -rpcpassword=toor -rpcport=8332";

            return View("CryptoCurrency", PaymentTypeConfig);
        }

        public IActionResult Doge()
        {
            db = new MarketBotDbContext();

            PaymentTypeEnum = PaymentTypeEnum.Doge;

            PaymentTypeConfig = db.PaymentTypeConfig.Where(p => p.PaymentId == PaymentType.GetTypeId(PaymentTypeEnum)).OrderByDescending(p => p.Id).FirstOrDefault();

            if (PaymentTypeConfig == null)
            {
                PaymentTypeConfig = new PaymentTypeConfig
                {
                    Host = "127.0.0.1",
                    Login = "root",
                    Pass = "toor",
                    Port = "8332",
                    Enable = true,
                    PaymentId = PaymentType.GetTypeId(PaymentTypeEnum)
                };

            }

            ViewBag.Title = "Doge";
            ViewBag.Text = "В папке с установленными Doge Core создайте бат файл.Сохраните и запустите этот бат файл и дождитесь синхронизации базы данных (Размер базы данных более 20гб)." +
                "Содержимое бат файла:";
            ViewBag.Bat = "dogecoin-qt.exe -server -rest -rpcuser=root -rpcpassword=toor -rpcport=8332";

            return View("CryptoCurrency", PaymentTypeConfig);
        }

        public IActionResult PaymentOnReceipt()
        {
            db = new MarketBotDbContext();

            return View(db.PaymentType.Where(p => p.Id == 1).FirstOrDefault());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult SavePaymentOnReceipt([FromBody] PaymentType _paymentType)
        {
            db = new MarketBotDbContext();

            var OnReceipt = db.PaymentType.Where(p => p.Id == 1).FirstOrDefault();

            if (OnReceipt != null && _paymentType != null)
            {
                OnReceipt.Enable = _paymentType.Enable;
                db.SaveChanges();
                return Json("Сохранено");
            }

            else
                return Json("Ошибка");
        }

        /// <summary>
        /// Сохранить изменения
        /// </summary>
        /// <param name="config"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Save([FromBody] PaymentTypeConfig config)
        {
            if(config!=null)
                PaymentTypeEnum = PaymentType.GetPaymentTypeEnum(config.PaymentId);

            if (config != null && config.Login == ""  && PaymentTypeEnum == PaymentTypeEnum.Qiwi)
                return Json("Заполните поле Номер телефона");

            if (config != null && config.Pass == "" && PaymentTypeEnum == PaymentTypeEnum.Qiwi)
                return Json("Заполните поле Токен доступа");

            if (config != null && config.Pass == "" && PaymentTypeEnum == PaymentTypeEnum.Litecoin)
                return Json("Заполните поле Пароль");

            if (config != null && config.Login == "" && PaymentTypeEnum == PaymentTypeEnum.Litecoin)
                return Json("Заполните поле Логин");

            if (config != null && config.Host == "" && PaymentTypeEnum == PaymentTypeEnum.Litecoin)
                return Json("Заполните поле Адрес RPC сервера");

            if (config != null && config.Port == "" && PaymentTypeEnum == PaymentTypeEnum.Litecoin)
                return Json("Заполните поле Порт RPC сервера");

            if (config != null && SaveChanges(config)>=0)
                return Json("Сохранено");
            
            else
                return Json("Ошибка"); 
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="config"></param>
        /// <returns></returns>
        /// 
        [HttpGet]
        public IActionResult Delete (int id)
        {
            if (id > 0)
            {
                db = new MarketBotDbContext();

                var config = db.PaymentTypeConfig.Find(id);

                db.PaymentTypeConfig.Remove(config);

                db.SaveChanges();
              
            }

            return RedirectToAction("Qiwi");
        }

        [HttpPost]

        public IActionResult EnableQiwi([FromBody] PaymentType paymentType)
        {
            if (paymentType != null)
            {
                db = new MarketBotDbContext();

                var type = db.PaymentType.Find(paymentType.Id);

                type.Enable = paymentType.Enable;

                db.SaveChanges();

                return Json("Сохранено");
            }

            else
                return Json("Ошибка");
        }

        [HttpGet]

        public IActionResult AddQiwi(string telephone, string token)
        {
            db = new MarketBotDbContext();

            if (telephone != null && token != null)
            {
                PaymentTypeConfig = new PaymentTypeConfig
                {
                    Host = "https://qiwi.com/api",
                    Login = telephone,
                    Pass = token,
                    Port = "80",
                    Enable = true,
                    PaymentId = PaymentType.GetTypeId(PaymentTypeEnum.Qiwi)
                };

                db.PaymentTypeConfig.Add(PaymentTypeConfig);

                db.SaveChanges();
            }

            return RedirectToAction("Qiwi");
        }

        /// <summary>
        /// Сохранить изменения в бд
        /// </summary>
        /// <param name="config"></param>

MyTelegramBot/Views/PayConfig/CryptoCurrency.cshtml
@model MyTelegramBot.PaymentTypeConfig
@{
    ViewData["Title"] = ViewBag.Title;
    Layout = "_Layout";
}
<!DOCTYPE html>

<h3>@ViewBag.Text</h3>
<h4><code>@ViewBag.Bat</code></h4>

@using (Html.BeginForm("Save", "PayConfig", FormMethod.Post))
    {

        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.PaymentId)
        <p>
        <label>
        Логин для подключения к RPC
        </label><br />
        @Html.TextBoxFor(m => m.Login, new { @class = "form-control" })
        </p>
        <p>
        <label>
        Пароль для подключения к RPC
        </label><br />
        @Html.TextBoxFor(m => m.Pass, new { @class = "form-control" })
        </p>

        <p>
            <label>
                Адрес RPC сервера
            </label>
            @Html.TextBoxFor(m=>m.Host, new { @class = "form-control" })
        </p>

        <p>
            <label>
                Порт RPC сервера
            </label>
            @Html.TextBoxFor(m => m.Port, new { @class = "form-control" })
        </p>

        <p>
            <label>
                Метод оплаты доступен для пользователей
            </label><br />
            @Html.CheckBoxFor(m=>Model.Enable, new { @class = "form-control" })
        </p>

}
    <input type="button" value="Тест" class="btn btn-success" onclick="ajaxTest();" />

<input type="button" value="Сохранить изменения" class="btn btn-success" onclick="ajaxSave();" />

    <script type="text/javascript">
        function ajaxTest()
        {
            var Config = {
                'Host': $("#Host").val(),
                'Login': $("#Login").val(),
                'Pass': $("#Pass").val(),
                'Port' : $("#Port").val(),
                Enable: $("#Enable").val(),
                PaymentId:@Model.PaymentId
            }
        $.ajax({
            type: "POST",
            url: 'TestConnection',
            data: JSON.stringify(Config),
            contentType: "application/json; charset=utf-8",
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function (data) {
            alert(data);

        })
        }
    </script>

<script type="text/javascript">
        function ajaxSave()
        {
            var Cgf = {
                'Id': $("#Id").val(),
                'Host': $("#Host").val(),
                'Login': $("#Login").val(),
                'Pass': $("#Pass").val(),
                'Port' : $("#Port").val(),
                Enable: $("#Enable").prop("checked"),
                PaymentId:@Model.PaymentId
            }
            $.ajax({
                type: "POST",
                url: 'Save',
                data: JSON.stringify(Cgf),
                contentType: "application/json; charset=utf-8",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-TOKEN",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                dataType: "json"
            }).done(function (data) {
                alert(data);

            })
        }
</script>

MyTelegramBot/Views/PayConfig/PaymentOnReceipt.cshtml
@model MyTelegramBot.PaymentType
@{
    //ViewData["Title"] = "Список смартфонов";
    Layout = "_Layout";
}
<!DOCTYPE html>
<h3>Оплата при получении</h3> 

@using (Html.BeginForm("SavePaymentOnReceipt", "PayConfig", FormMethod.Post))
    {

        @Html.HiddenFor(m => m.Id)
        <p>
        <label>
        Способ оплаты доступен для пользователей
        </label><br />
        @Html.CheckBoxFor(m => m.Enable, new { @class = "form-control" })
        </p>

}

<input type="button" value="Сохранить изменения" class="btn btn-success" onclick="ajaxSave();" />

<script type="text/javascript">
        function ajaxSave()
        {
            var Cgf = {
                Enable: $("#Enable").prop("checked"),
                Id:@Model.Id
            }
        $.ajax({
            type: "POST",
            url: 'SavePaymentOnReceipt',
            data: JSON.stringify(Cgf),
            contentType: "application/json; charset=utf-8",
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            dataType: "json"
        }).done(function (data) {
            alert(data);

        })
        }
</script>

MyTelegramBot/Views/PayConfig/Qiwi.cshtml
@model Tuple<List<MyTelegramBot.PaymentTypeConfig>, MyTelegramBot.PaymentType>
@{
    //ViewData["Title"] = "Список смартфонов";
    Layout = "_Layout";
    int counter = 1;
}
<!DOCTYPE html>
<h3>Настройка Qiwi. Что бы получить токен доступа пройдите по ссылке <a href="https://qiwi.com/api">https://qiwi.com/api</a></h3> 

@Html.HiddenFor(m => m.Item2.Id)
<p>
    <label>
        Способ оплаты доступен для пользователей
    </label><br />
    @Html.CheckBoxFor(m => m.Item2.Enable, new { @class = "form-control" })
</p>
<br /><input type="submit" value="Сохранить" class="btn btn-success" onclick="ajaxEnable();" />


<div class="form-group row">
@using (Html.BeginForm("AddQiwi", "PayConfig", FormMethod.Get))
{

    <br />
    <div class="col-xs-3">
        <label for="ex1">Номер телефона</label>
        <input class="form-control" id="telephone" type="text" name="telephone">
    </div>
    <div class="col-xs-4">
        <label for="ex2">Токен доступа</label>
        <input class="form-control" id="token" type="text" name="token">
    </div>
    <div class="col-xs-2">
        <br /><input type="submit" value="Добавить" class="btn btn-success" />
    </div>
}
</div>




@foreach (MyTelegramBot.PaymentTypeConfig cgf in Model.Item1)
{
    <br />

         @Html.HiddenFor(m => cgf.Id, new { @id = "Id" + counter })
        @Html.HiddenFor(m => cgf.PaymentId)

    <div class="form-group row">
        <div class="col-xs-4">
            <label for="ex1">Номер телефона</label>
            @Html.TextBoxFor(m => cgf.Login, new { @class = "form-control", @id = "Login" + counter })
        </div>
        <div class="col-xs-4">
            <label for="ex2">Токен доступа</label>
            @Html.TextBoxFor(m => cgf.Pass, new { @class = "form-control", @id = "Pass" + counter })
        </div>

    </div>

        <input type="button" value="Тест QIWI" class="btn btn-success" onclick="ajaxTest($('#Login'+@counter).val(),$('#Pass'+@counter).val());"  />

        <input type="button" value="Сохранить изменения" class="btn btn-success" onclick="ajaxSave($('#Login'+@counter).val(),$('#Pass'+@counter).val(),$('#Id'+@counter).val());"  />

        <a href="~/PayConfig/Delete?Id=@cgf.Id" class="btn btn-danger" role="button">Удалить</a>

    counter++;
}

<script type="text/javascript">
        function ajaxTest(Login, Pass)
        {
            var Config = {
                'Host': 'https://qiwi.com/api',
                'Login': Login,
                'Pass': Pass,
                'Port' : '80',
                Enable: 'true',
                PaymentId:'2'
            }
        $.ajax({
            type: "POST",
            url: 'TestConnection',
            data: JSON.stringify(Config),
            contentType: "application/json; charset=utf-8",
            beforeSend: function (xhr) {
            },
            dataType: "json"
        }).done(function (data) {
            alert(data);

        })
        }
</script>

<script type="text/javascript">
        function ajaxSave(Login, Pass,Id) {
            var Config = {
                'Id': Id,
                'Host': 'https://qiwi.com/api',
                'Login': Login,
                'Pass': Pass,
                'Port': '80',
                Enable: 'true',
                PaymentId: '2'
            }
            $.ajax({
                type: "POST",
                url: 'Save',
                data: JSON.stringify(Config),
                contentType: "application/json; charset=utf-8",
                beforeSend: function (xhr) {
                },
                dataType: "json"
            }).done(function (data) {
                alert(data);

            })
        }
</script>

<script type="text/javascript">
        function ajaxEnable() {
            var Config = {
                'Id': $('#Item2_Id').val(),
                Enable: $('#Item2_Enable').prop('checked'),
            }
            $.ajax({
                type: "POST",
                url: 'EnableQiwi',
                data: JSON.stringify(Config),
                contentType: "application/json; charset=utf-8",
                beforeSend: function (xhr) {
                },
                dataType: "json"
            }).done(function (data) {
                alert(data);

            })
        }
</script>